import React, { useState } from 'react';
import { ArrowLeft, Star, DollarSign, Play, User, Calendar, TrendingUp, MessageSquare, Share2 } from 'lucide-react';
import { useApp } from '../contexts/AppContext';
import { InputField } from '../types';

export function AgentDetail() {
  const { agents, selectedAgentId, navigate, isAuthenticated } = useApp();
  const [inputValues, setInputValues] = useState<Record<string, any>>({});
  const [isRunning, setIsRunning] = useState(false);
  const [result, setResult] = useState<string>('');

  const agent = agents.find(a => a.id === selectedAgentId);

  if (!agent) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">Agent not found</h2>
          <button
            onClick={() => navigate('marketplace')}
            className="bg-primary-600 text-white px-6 py-3 rounded-lg hover:bg-primary-700 transition-colors"
          >
            Back to Marketplace
          </button>
        </div>
      </div>
    );
  }

  const handleInputChange = (field: InputField, value: any) => {
    setInputValues(prev => ({
      ...prev,
      [field.name]: value
    }));
  };

  const handleRunAgent = async () => {
    if (!isAuthenticated) {
      // In a real app, this would show login modal
      alert('Please sign in to use agents');
      return;
    }

    setIsRunning(true);
    
    // Simulate AI processing
    setTimeout(() => {
      const mockResponse = `Based on your inputs, here's a comprehensive response that demonstrates the agent's capabilities. This would be generated by the AI using the creator's custom system prompt and your specific inputs.

This is a mock response for demonstration purposes. In a real implementation, this would be the actual AI-generated content based on the agent's configuration.`;
      
      setResult(mockResponse);
      setIsRunning(false);
    }, 3000);
  };

  const isFormValid = agent.inputSchema.every(field => 
    !field.required || (inputValues[field.name] && inputValues[field.name].toString().trim())
  );

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Back Button */}
        <button
          onClick={() => navigate('marketplace')}
          className="flex items-center space-x-2 text-gray-600 hover:text-primary-600 transition-colors mb-8"
        >
          <ArrowLeft className="h-5 w-5" />
          <span>Back to Marketplace</span>
        </button>

        <div className="grid lg:grid-cols-3 gap-8">
          {/* Main Content */}
          <div className="lg:col-span-2 space-y-8">
            {/* Agent Header */}
            <div className="bg-white rounded-2xl shadow-sm border border-gray-200 p-8">
              <div className="flex items-start justify-between mb-6">
                <div>
                  <h1 className="text-3xl font-bold text-gray-900 mb-4">
                    {agent.name}
                  </h1>
                  <p className="text-lg text-gray-600 leading-relaxed">
                    {agent.description}
                  </p>
                </div>
                <button className="p-2 text-gray-400 hover:text-gray-600 transition-colors">
                  <Share2 className="h-5 w-5" />
                </button>
              </div>

              <div className="flex items-center justify-between border-t pt-6">
                <div className="flex items-center space-x-6">
                  <div className="flex items-center space-x-2">
                    <div className="flex items-center space-x-1">
                      {[...Array(5)].map((_, i) => (
                        <Star
                          key={i}
                          className={`h-4 w-4 ${
                            i < Math.floor(agent.rating)
                              ? 'text-yellow-400 fill-current'
                              : 'text-gray-300'
                          }`}
                        />
                      ))}
                    </div>
                    <span className="font-medium text-gray-900">
                      {agent.rating}
                    </span>
                    <span className="text-gray-500">
                      ({agent.totalUses.toLocaleString()} uses)
                    </span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <TrendingUp className="h-4 w-4 text-secondary-500" />
                    <span className="text-gray-600">Trending</span>
                  </div>
                </div>
                <div className="flex items-center space-x-1 bg-accent-50 px-3 py-2 rounded-full">
                  <DollarSign className="h-4 w-4 text-accent-600" />
                  <span className="text-lg font-semibold text-accent-700">
                    ${agent.pricePerUse}
                  </span>
                  <span className="text-sm text-accent-600">per use</span>
                </div>
              </div>
            </div>

            {/* Creator Info */}
            <div className="bg-white rounded-2xl shadow-sm border border-gray-200 p-6">
              <h3 className="text-lg font-semibold text-gray-900 mb-4">
                About the Creator
              </h3>
              <div className="flex items-center space-x-4">
                <div className="w-12 h-12 bg-primary-500 rounded-full flex items-center justify-center">
                  <User className="h-6 w-6 text-white" />
                </div>
                <div>
                  <h4 className="font-medium text-gray-900">{agent.creator.name}</h4>
                  <p className="text-gray-600">{agent.creator.email}</p>
                </div>
                <div className="ml-auto text-right">
                  <div className="flex items-center space-x-1 text-sm text-gray-500">
                    <Calendar className="h-4 w-4" />
                    <span>Joined {new Date(agent.creator.createdAt).toLocaleDateString()}</span>
                  </div>
                </div>
              </div>
            </div>

            {/* Tags and Category */}
            <div className="bg-white rounded-2xl shadow-sm border border-gray-200 p-6">
              <h3 className="text-lg font-semibold text-gray-900 mb-4">
                Tags & Category
              </h3>
              <div className="flex items-center justify-between">
                <div className="flex flex-wrap gap-2">
                  {agent.tags.map((tag) => (
                    <span
                      key={tag}
                      className="px-3 py-1 bg-primary-50 text-primary-700 rounded-full text-sm font-medium"
                    >
                      {tag}
                    </span>
                  ))}
                </div>
                <span className="px-4 py-2 bg-secondary-50 text-secondary-700 rounded-lg font-medium">
                  {agent.category}
                </span>
              </div>
            </div>
          </div>

          {/* Sidebar - Try Agent */}
          <div className="space-y-6">
            <div className="bg-white rounded-2xl shadow-sm border border-gray-200 p-6 sticky top-8">
              <div className="flex items-center space-x-2 mb-6">
                <MessageSquare className="h-5 w-5 text-primary-600" />
                <h3 className="text-lg font-semibold text-gray-900">
                  Try This Agent
                </h3>
              </div>

              <div className="space-y-4">
                {agent.inputSchema.map((field) => (
                  <div key={field.name}>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      {field.label}
                      {field.required && <span className="text-red-500 ml-1">*</span>}
                    </label>
                    {field.type === 'textarea' ? (
                      <textarea
                        rows={4}
                        placeholder={field.placeholder}
                        className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent resize-none"
                        value={inputValues[field.name] || ''}
                        onChange={(e) => handleInputChange(field, e.target.value)}
                      />
                    ) : field.type === 'select' ? (
                      <select
                        className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                        value={inputValues[field.name] || ''}
                        onChange={(e) => handleInputChange(field, e.target.value)}
                      >
                        <option value="">Select {field.label}</option>
                        {field.options?.map((option) => (
                          <option key={option} value={option}>
                            {option}
                          </option>
                        ))}
                      </select>
                    ) : (
                      <input
                        type={field.type}
                        placeholder={field.placeholder}
                        className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                        value={inputValues[field.name] || ''}
                        onChange={(e) => handleInputChange(field, field.type === 'number' ? parseFloat(e.target.value) : e.target.value)}
                      />
                    )}
                  </div>
                ))}

                <button
                  onClick={handleRunAgent}
                  disabled={!isFormValid || isRunning}
                  className="w-full bg-primary-600 text-white py-3 rounded-lg font-medium hover:bg-primary-700 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors flex items-center justify-center space-x-2"
                >
                  {isRunning ? (
                    <>
                      <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
                      <span>Processing...</span>
                    </>
                  ) : (
                    <>
                      <Play className="h-4 w-4" />
                      <span>Run Agent</span>
                    </>
                  )}
                </button>

                {result && (
                  <div className="mt-6 p-4 bg-gray-50 rounded-lg">
                    <h4 className="font-medium text-gray-900 mb-2">Result:</h4>
                    <div className="text-gray-700 whitespace-pre-wrap text-sm leading-relaxed">
                      {result}
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}